export const siteConfig = {
  name: "Aastha",
  fullName: "Aastha Multi Speciality Hospital",
  tagline: "Advanced Care, Amidst the Mountains.",
  description:
    "Aastha Multi Speciality Hospital brings world-class medical care to the hills — expert specialists, modern facilities, and compassionate service for the people of Himachal Pradesh.",
  phone: "+91 98885 45809",
  emergency: "1066",
  emergencyFull: "+91 98765 11066",
  whatsapp: "+91 98885 45809",
  email: "care@Aasthahospital.in",
  address: {
    line1: "Ridge Road, Tutu, Shimla",
    line2: "Himachal Pradesh — 171011",
  },
  hours: {
    opd: {
      days: [1, 2, 3, 4, 5, 6], // Mon–Sat
      startHour: 8,
      endHour: 20,
      label: "Mon–Sat · 8 AM – 8 PM",
    },
    emergency: "24 / 7 / 365",
  },
  social: {
    facebook: "#",
    instagram: "#",
    whatsapp: "#",
    twitter: "#",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Departments", href: "/departments", caret: true },
    { label: "Doctors", href: "/doctors" },
    { label: "Services", href: "/services", caret: true },
    { label: "Patients", href: "/patients", caret: true },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  quickAccess: [
    { icon: "search", label: "Find a Doctor", href: "/doctors" },
    { icon: "calendar", label: "Book Appointment", href: "#book" },
    { icon: "clock", label: "OPD Schedule", href: "/patients/opd" },
    { icon: "flask", label: "Labs & Reports", href: "/patients/labs" },
    { icon: "blood", label: "Blood Bank", href: "/services/blood-bank" },
    { icon: "pill", label: "Pharmacy", href: "/services/pharmacy" },
  ],
  // Wave shape per line i: M 0 (yStart+i×ySpacing) Q cp1x (cp1y+i×ySpacing) cp2x (cp2y+i×ySpacing) T endX (endY+i×ySpacing)
  topoLines: {
    color: "#0D9488",
    sizes: {
      small: {
        opacity: 0.09,
        count: 20,
        strokeWidth: 0.9,
        viewBox: "0 0 1440 560",
        preserveAspectRatio: "xMidYMid slice" as const,
        defaultClassName: "absolute inset-0 w-full h-full pointer-events-none",
        mask: { fadeStart: 35, fadeEnd: 60 },
        wave: {
          startX: 0,
          yStart: 30,
          ySpacing: 26,
          cp1x: 380,
          cp1y: 5,
          cp2x: 780,
          cp2y: 80,
          endX: 1440,
          endY: 33,
        },
      },
      medium: {
        opacity: 0.1,
        count: 14,
        strokeWidth: 1.1,
        viewBox: "0 0 1440 560",
        preserveAspectRatio: "xMidYMid slice" as const,
        defaultClassName: "absolute inset-0 w-full h-full pointer-events-none",
        mask: { fadeStart: 35, fadeEnd: 60 },
        wave: {
          startX: 0,
          yStart: 70,
          ySpacing: 38,
          cp1x: 360,
          cp1y: 20,
          cp2x: 720,
          cp2y: 105,
          endX: 1440,
          endY: 73,
        },
      },
      large: {
        opacity: 0.13,
        count: 16,
        strokeWidth: 1.2,
        viewBox: "0 0 1440 560",
        preserveAspectRatio: "xMidYMid slice" as const,
        defaultClassName: "absolute inset-0 w-full h-full pointer-events-none",
        mask: { fadeStart: 38, fadeEnd: 68 },
        wave: {
          startX: 0,
          yStart: 80,
          ySpacing: 38,
          cp1x: 360,
          cp1y: 30,
          cp2x: 720,
          cp2y: 110,
          endX: 1440,
          endY: 85,
        },
      },
    },
  },

  footerLinks: {
    quick: [
      { label: "Home", href: "/" },
      { label: "About Us", href: "/about" },
      { label: "Departments", href: "/departments" },
      { label: "Our Doctors", href: "/doctors" },
      { label: "Services", href: "/services" },
      { label: "Contact", href: "/contact" },
    ],
    patient: [
      { label: "Book Appointment", href: "/#book" },
      { label: "OPD Schedule", href: "/patients/opd" },
      { label: "Patient Portal", href: "/patients/portal" },
      { label: "Labs & Reports", href: "/patients/labs" },
      { label: "Insurance / TPA", href: "/patients/insurance" },
      { label: "Feedback", href: "/patients/feedback" },
    ],
  },
};
